### ISSUE TITLE
ACL embedded in EntityBean instance

### ISSUE THREAD

**Issue by mcapitanio** [ArneLimburg/jpasecurity#1]
@ArneLimburg Our need is ACL on JPA and the availability of the ACL to a Single Page Application. 
This is a possible scenario for us: we have a rest method which retrieves a list of Loans from the database. Every loan is owened by a specific Organization Unit. Only roles from that OU can see the Loans in VIEW, but only the owner of the Loan is allowed to MODIFY it.

With jpasecurity can I know, of the all Loan instances retrieved from the database, which has just the VIEW right and which has the MODIFY right?
This information is necessary to bring the ACL to the Model object and finally to the SPA which could be able to use it for example for showing or not an "Update" button on the user interface.

**Comment by ArneLimburg** [comment]
This is perfectly doable with JPA Securtiy. With access rules configured right, you would just retrieve the loans from database of which the current user has view rights. Afterwards you could check with the AccessManager, to which of them the user has MODIFY rights. You can receive the AccessManager by calling EntityManager.unwrap(AccessManager.class);

**Comment by mcapitanio** [comment]
@ArneLimburg Thanks! I didn't look at the AccessManager method, just search for the SecureEntity class, but maybe there was a deep refactoring from your original project. Very interesting project and we are evaluating to use it and contribute if necessary!

**Comment by mcapitanio** [comment]
@ArneLimburg Maybe an enhancement could be use a bitmask to grant several right at once.

**Comment by ArneLimburg** [comment]
You are right, the complete proxy code was removed (together with the SecureEntity interface), because it was just to slow.

**Comment by shot-mk** [comment]
@ArneLimburg so now (since all proxy code was removed) when i am getting entity from database, all the sub queries for lazy loading it's properties will not  be filtered by security? And if i want to get something filtered i need to manually call `SecureCollections.secureList()` or in case of not collection field `AccessManager.isAccessible(accessType, entity) ? entity : null; ` ?  Is it the only option currently available?

**Comment by ArneLimburg** [comment]
When you register SecureEntityListener lazy loaded properties are checked for read access. If read access is not permitted, an exception is thrown. Properties are not filtered automatically any more and need to be filtered manually if needed as you wrote.
