### ISSUE TITLE
EntitymanagerEvaluator can not handle nested Subselects

### ISSUE THREAD

**Issue by Rene-Frerichs** [ArneLimburg/jpasecurity#76]
The following statement throws a NotEvaluatableException instead of evaluating:
SELECT innerBean FROM MethodAccessTestBean innerBean WHERE innerBean = bean AND  EXISTS ( SELECT parent FROM MethodAccessTestBean nestedInnerBean LEFT OUTER JOIN nestedInnerBean.parent parent  WHERE nestedInnerBean = this AND innerBean.parent = parent)

**Comment by ArneLimburg** [comment]
Fixed
