### ISSUE TITLE
Update grammar to JPA 2.1

### ISSUE THREAD

**Issue by ArneLimburg** [ArneLimburg/jpasecurity#9]
The current grammar does not contain all JPA 2.1 features.

**Comment by CSchulz** [comment]
OpenJPA will be not able to support JPA 2.1 features, because there is no release.
EclipseLink is already able to handle JPA 2.1 features.

http://openjpa.apache.org/downloads.html

**Comment by ArneLimburg** [comment]
With the INDEX keyword all 2.1 grammar features are supported
